### PR TITLE
Add travis test for ROS jade

### PR DESCRIPTION
**Pull request by wkentaro**
Please wait for https://github.com/jsk-ros-pkg/jsk_travis/pull/102 to be merged
and submodules to be updated.

### CODE REVIEW

**Comment by k-okada** [comment]
```
-- run_tests.py: verify result "/workspace/ros/ws_2014-semi/build/jsk_2014_picking_challenge/test_results/jsk_2014_picking_challenge/nosetests-test.test_robot_input.py.xml"


Built target _run_tests_jsk_2014_picking_challenge_nosetests_test.test_robot_input.py


Scanning dependencies of target _run_tests_jsk_2014_picking_challenge_nosetests


Built target _run_tests_jsk_2014_picking_challenge_nosetests


;; loading roseus("") on euslisp((9.12 host08.storm.ros.org Fri May 22 20:44:31 UTC 2015  1.0.6))


[ERROR] [1435037463.443262996]: Could not find roseus messages for pr2_msgs under (/workspace/ros/ws_2014-semi/devel/share/roseus/ros /workspace/ros/ws_2014-semi/devel/share/roseus/ros /opt/ros/indigo/share/roseus/ros)


try rosrun roseus generate-all-msg-srv.sh pr2_msgs


[ERROR] [1435037463.443482127]: Could not find nil/manifest.l


try rosrun roseus generate-all-msg-srv.sh pr2_msgs


[ERROR] [1435037463.447848546]: Could not find roseus messages for pr2_controllers_msgs under (/workspace/ros/ws_2014-semi/devel/share/roseus/ros /workspace/ros/ws_2014-semi/devel/share/roseus/ros /opt/ros/indigo/share/roseus/ros)


try rosrun roseus generate-all-msg-srv.sh pr2_controllers_msgs


[ERROR] [1435037463.448013096]: Could not find nil/manifest.l


try rosrun roseus generate-all-msg-srv.sh pr2_controllers_msgs


[ERROR] [1435037463.448171106]: Could not find roseus messages for control_msgs under (/workspace/ros/ws_2014-semi/devel/share/roseus/ros /workspace/ros/ws_2014-semi/devel/share/roseus/ros /opt/ros/indigo/share/roseus/ros)


try rosrun roseus generate-all-msg-srv.sh control_msgs


[ERROR] [1435037463.448298376]: Could not find nil/manifest.l


try rosrun roseus generate-all-msg-srv.sh control_msgs


/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl roseus-error: no such package CONTROL_MSGS in (apply #'ros::load-org-for-ros ros::fullname args), exitting...


testrobot_test ... FAILURE!


FAILURE: test [robot_test] did not generate test results


  File "/usr/lib/python2.7/unittest/case.py", line 331, in run


    testMethod()


  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 160, in fn


    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)


  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue


    raise self.failureException(msg)
```
なんかおかしい？

**Comment by wkentaro** [comment]
必要なメッセージのmanifest.lが作られていないのかと思いますが、ちょっと原因がわからないですね。
geneusとjsk_roseusを更新して再テストしたいので、リリースを待つことにしたいと思います。

On Tue, Jun 23, 2015 at 3:41 PM, Kei Okada <notifications@github.com> wrote:

> -- run_tests.py: verify result "/workspace/ros/ws_2014-semi/build/jsk_2014_picking_challenge/test_results/jsk_2014_picking_challenge/nosetests-test.test_robot_input.py.xml"
>
>
> Built target _run_tests_jsk_2014_picking_challenge_nosetests_test.test_robot_input.py
>
>
> Scanning dependencies of target _run_tests_jsk_2014_picking_challenge_nosetests
>
>
> Built target _run_tests_jsk_2014_picking_challenge_nosetests
>
>
> ;; loading roseus("") on euslisp((9.12 host08.storm.ros.org Fri May 22 20:44:31 UTC 2015  1.0.6))
>
>
> [ERROR] [1435037463.443262996]: Could not find roseus messages for pr2_msgs under (/workspace/ros/ws_2014-semi/devel/share/roseus/ros /workspace/ros/ws_2014-semi/devel/share/roseus/ros /opt/ros/indigo/share/roseus/ros)
>
>
> try rosrun roseus generate-all-msg-srv.sh pr2_msgs
>
>
> [ERROR] [1435037463.443482127]: Could not find nil/manifest.l
>
>
> try rosrun roseus generate-all-msg-srv.sh pr2_msgs
>
>
> [ERROR] [1435037463.447848546]: Could not find roseus messages for pr2_controllers_msgs under (/workspace/ros/ws_2014-semi/devel/share/roseus/ros /workspace/ros/ws_2014-semi/devel/share/roseus/ros /opt/ros/indigo/share/roseus/ros)
>
>
> try rosrun roseus generate-all-msg-srv.sh pr2_controllers_msgs
>
>
> [ERROR] [1435037463.448013096]: Could not find nil/manifest.l
>
>
> try rosrun roseus generate-all-msg-srv.sh pr2_controllers_msgs
>
>
> [ERROR] [1435037463.448171106]: Could not find roseus messages for control_msgs under (/workspace/ros/ws_2014-semi/devel/share/roseus/ros /workspace/ros/ws_2014-semi/devel/share/roseus/ros /opt/ros/indigo/share/roseus/ros)
>
>
> try rosrun roseus generate-all-msg-srv.sh control_msgs
>
>
> [ERROR] [1435037463.448298376]: Could not find nil/manifest.l
>
>
> try rosrun roseus generate-all-msg-srv.sh control_msgs
>
>
> /opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl roseus-error: no such package CONTROL_MSGS in (apply #'ros::load-org-for-ros ros::fullname args), exitting...
>
>
> testrobot_test ... FAILURE!
>
>
> FAILURE: test [robot_test] did not generate test results
>
>
>   File "/usr/lib/python2.7/unittest/case.py", line 331, in run
>
>
>     testMethod()
>
>
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 160, in fn
>
>
>     self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)
>
>
>   File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
>
>
>     raise self.failureException(msg)
>
> なんかおかしい？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/pull/812#issuecomment-114377797>.
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
ちゃんとみていないけど，一応全部最新になっている気がする．
http://www.ros.org/debbuild/indigo.html?q=eus

**Comment by wkentaro** [comment]
```
$ sudo apt-get update
$ apt-cache show ros-hydro-geneus
Package: ros-hydro-geneus
Version: 2.2.2-0precise-20150601-0156-+0000
Architecture: amd64
Maintainer: Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>
Installed-Size: 179
Depends: python-rospkg, ros-hydro-genmsg
Priority: extra
Filename: pool/main/r/ros-hydro-geneus/ros-hydro-geneus_2.2.2-0precise-20150601-0156-+0000_amd64.deb
Size: 30136
SHA256: b3c6984dc3d859bb3da7041538a51f185b7e6f7d3ee5432a5111533365af8826
SHA1: 5b4b055270fce2032d37bd543ec369ee7396671e
MD5sum: d164d910eea35958eb82aa2f59476712
Description: EusLisp ROS message and service generators.
$ cat /etc/apt/sources.list.d/ros-latest.list
deb http://packages.ros.org/ros-shadow-fixed/ubuntu precise main
```

**Comment by wkentaro** [comment]
I can't install the latest geneus.

**Comment by wkentaro** [comment]
I'd like to use https://github.com/jsk-ros-pkg/jsk_roseus/pull/319 .
this error may be caused by ungenerated messages.

**Comment by k-okada** [comment]
http://www.ros.org/debbuild/hydro.html?q=geneus

2.2.3 is available on hydro too, as for jsk-ros-pkg/jsk_roseus#319,
restarted travis.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
I see.
but in my environment it does not updated by apt-get update.I dont know why.
I will wait for a while.

2015年6月23日火曜日、Kei Okada<notifications@github.com>さんは書きました:

> http://www.ros.org/debbuild/hydro.html?q=geneus
>
> 2.2.3 is available on hydro too, as for jsk-ros-pkg/jsk_roseus#319,
> restarted travis.
>
> --
> ◉ Kei Okada
>
>
> On Tue, Jun 23, 2015 at 5:38 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I'd like to use jsk-ros-pkg/jsk_roseus#319
> > <https://github.com/jsk-ros-pkg/jsk_roseus/pull/319> .
> > this error may be caused by ungenerated messages.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/start-jsk/2014-semi/pull/812#issuecomment-114407710
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/pull/812#issuecomment-114416616>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
please check /etc/apt/sources.list, it should point to shadow-fixed

--
◉ Kei Okada

**Comment by wkentaro** [comment]
昨日は何度`apt-get update`してもダメだったのですが、今日するとすべて
http://www.ros.org/debbuild/hydro.html?q=eus
にかかれているようにupdateされました。

日本からだと何かしらのタイムラグがあったりするのでしょうか。
（/etc/apt/source.list.d/ros-latest)は昨日も何度も確認しましたがshadow-fixedになっていました）

**Comment by k-okada** [comment]
mirrorつかっているとか？

--
◉ Kei Okada


2015-06-24 12:28 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
source.list.d/ros-latest.listはそんなことはないと思います
```
% cat ros-latest.list
deb http://packages.ros.org/ros-shadow-fixed/ubuntu trusty main
```

**Comment by 130s** [comment]
http://lists.ros.org/pipermail/ros-release で念の為聞くのが良い気がします．

今回のは shadow-fixed なので関係するかは分かりませんが，正式 repo では sync がなされてない (http://www.ros.org/debbuild の表示と[実際](http://packages.ros.org/ros-shadow-fixed/ubuntu/dists/precise/main/binary-amd64/Packages)とが合っていない) のは何度か経験してます ([例](http://lists.ros.org/pipermail/ros-release/2015-April/004623.html))．アジアからのアクセスで起こる cornercase を発見してないとも限らないですし．

**Comment by wkentaro** [comment]
ありがとうございます。メール送りました。

2015-06-24 12:49 GMT+09:00 Isaac I.Y. Saito <notifications@github.com>:

> http://lists.ros.org/pipermail/ros-release で念の為聞くのが良い気がします．
>
> 今回のは shadow-fixed なので関係するかは分かりませんが，正式 repo では sync がなされてない (
> http://www.ros.org/debbuild の表示と実際
> <http://packages.ros.org/ros-shadow-fixed/ubuntu/dists/precise/main/binary-amd64/Packages>とが合っていない)
> のは何度か経験してます (例
> <http://lists.ros.org/pipermail/ros-release/2015-April/004623.html>)．アジアからのアクセスで起こる
> cornercase を発見してないとも限らないですし．
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/pull/812#issuecomment-114720317>.
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Pull request closed without merging**
