### PR TITLE
Add travis test for ROS jade

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
seems difficult without ros/urdfdom release.
https://github.com/ros/urdfdom

**Comment by k-okada** [comment]
what is the name of package you're missin on jade environment
urdf has been released via defualt  ubuntu repository since indigo ->
http://packages.ubuntu.com/source/vivid/urdfdom

--
◉ Kei Okada

**Comment by wkentaro** [comment]
I think it is urdfdom.
The error output is below
~~~

[euscollada] CMake Error at /opt/ros/jade/share/catkin/cmake/catkinConfig.cmake:75 (find_package): 

[euscollada]   Could not find a package configuration file provided by "urdfdom" with any 

[euscollada]   of the following names:                                          

[euscollada]                                                                    

[euscollada]     urdfdomConfig.cmake                                            

[euscollada]     urdfdom-config.cmake                                           

[euscollada]                                                                    

[euscollada]   Add the installation prefix of "urdfdom" to CMAKE_PREFIX_PATH or set 

[euscollada]   "urdfdom_DIR" to a directory containing one of the above files.  If 

[euscollada]   "urdfdom" provides a separate development package or SDK, be sure it has 

[euscollada]   been installed.                                                  

[euscollada] Call Stack (most recent call first):                               

[euscollada]   CMakeLists.txt:8 (find_package)                                  

[euscollada]                                                                    

[euscollada]                           
~~~

**Comment by k-okada** [comment]
that should work , please check if urdfdom is installed in travis process
and also check if there are any change on urdfrom itself.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
jsk_model_tools does not pass test on jade. So this is problem in upstream.

**Comment by wkentaro** [comment]
created issue https://github.com/jsk-ros-pkg/jsk_model_tools/issues/143

**Comment by wkentaro** [comment]
jade remains as allow_failure.
because jsk_robot has a lot of dependencies which is not yet released as deb package.
(mainly pr2_**)

**Pull request merged**
